// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/preprocess-text.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
async function invokeEdge(name, body) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  const res = await fetch(`${url}/functions/v1/${name}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${key}`,
      apikey: key
    },
    body: JSON.stringify(body)
  });
  if (!res.ok) throw new Error(`${name} failed: ${res.status} ${await res.text()}`);
  return res.json();
}
var preprocess_text_default = defineTool({
  name: "preprocess_text",
  title: "Preprocess CTI text",
  description: "Clean and defang a CTI passage (URLs, hashes, IPs). Returns cleaned text, detected IOCs, source-type guess and a reliability score. Read-only.",
  inputSchema: {
    text: z.string().min(10).describe("Raw CTI passage (report, advisory, blog, etc.)."),
    source_type: z.string().optional().describe("Optional source-type hint (e.g. 'blog', 'advisory', 'report'). Defaults to auto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ text, source_type }) => {
    const data = await invokeEdge("threat-preprocess", {
      text,
      source_type: source_type ?? "auto",
      domain: "cti"
    });
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/extract-threats.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var extract_threats_default = defineTool2({
  name: "extract_threats",
  title: "Extract CTI knowledge graph (Pathway B)",
  description: "Run the deterministic Graph-Native extraction pipeline (Pathway B) on a CTI passage. Returns entities, relations, causal links and STIX-aligned graph metadata. Read-only \u2014 does not persist to the KG.",
  inputSchema: {
    text: z2.string().min(10).describe("CTI passage to extract from."),
    mode: z2.enum(["full", "ner", "re", "causality"]).optional().describe("Extraction mode. Default 'full'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ text, mode }) => {
    const data = await invokeEdge("threat-extract", {
      text,
      mode: mode ?? "full",
      source_type: "report",
      source_reliability: 0.8,
      rag_context: "",
      deterministic: true,
      temperature: 0,
      seed: 42,
      domain: "cti"
    });
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/extract-hyperedges.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var extract_hyperedges_default = defineTool3({
  name: "extract_hyperedges",
  title: "Extract hyperedges (Pathway C, CTI only)",
  description: "Run the hyperedge-native extractor (Pathway C) on a CTI passage. Preserves n-ary events (kill-chains, campaigns, fusion findings) as first-class hyperedges plus a derived triple projection. Preferred when \u22653 participants share a single event. Read-only.",
  inputSchema: {
    text: z3.string().min(10).describe("CTI passage to extract from.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ text }) => {
    const data = await invokeEdge("threat-extract-hyper", {
      text,
      source_type: "report",
      source_reliability: 0.8,
      rag_context: "",
      deterministic: true,
      temperature: 0,
      seed: 42,
      domain: "cti"
    });
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/query-kg.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
var query_kg_default = defineTool4({
  name: "query_threat_kg",
  title: "Query ThreatGraph KG (attribution / attack path)",
  description: "Attribute a threat actor or reconstruct an attack path from an extracted graph. Supply entities/relations/causal_links from `extract_threats` (or an equivalent shape). Read-only.",
  inputSchema: {
    query: z4.string().default("Identify the threat actor and reconstruct the attack chain").describe("Natural-language question, e.g. 'which actor is behind this campaign?'."),
    mode: z4.enum(["attribute", "attack_path"]).default("attribute"),
    entities: z4.array(z4.record(z4.unknown())).default([]).describe("Entities from extract_threats.ner.entities."),
    relations: z4.array(z4.record(z4.unknown())).default([]).describe("Relations from extract_threats.re.relations."),
    causal_links: z4.array(z4.record(z4.unknown())).default([]).describe("Causal links from extract_threats.causality.causal_links.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, mode, entities, relations, causal_links }) => {
    const data = await invokeEdge("threat-kg-query", {
      query,
      mode,
      entities,
      relations,
      causal_links,
      domain: "cti"
    });
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list-recent-reports.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
var list_recent_reports_default = defineTool5({
  name: "list_recent_reports",
  title: "List recent ingested CTI reports",
  description: "Return the most recent CTI reports already ingested into ThreatGraph (id, summary, source_type, created_at). Reads through the anon role \u2014 only rows RLS exposes publicly are returned.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(10).describe("Max rows (1\u201350).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("threat_reports").select("id, summary, source_type, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "threatgraph-mcp",
  title: "ThreatGraph MCP",
  version: "0.1.0",
  instructions: "Tools for the ThreatGraph research platform (CTI only). Use `preprocess_text` to clean/defang a passage and detect IOCs; `extract_threats` for the deterministic Graph-Native pipeline (Pathway B); `extract_hyperedges` for the n-ary hyperedge extractor (Pathway C, prefer when \u22653 actors/artefacts share one event); `query_threat_kg` for attribution or attack-path reconstruction against an extracted graph; `list_recent_reports` for what has already been ingested. All tools are read-only and do not persist to the KG. This is a public research endpoint \u2014 no user data.",
  tools: [
    preprocess_text_default,
    extract_threats_default,
    extract_hyperedges_default,
    query_kg_default,
    list_recent_reports_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
